# Generated by Django 4.2.6 on 2023-11-01 22:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0005_alter_route_type_of_measurement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flight",
            options={"ordering": ["-departure_time"]},
        ),
        migrations.AlterModelOptions(
            name="route",
            options={"ordering": ["source", "destination"]},
        ),
    ]
