# Generated by Django 4.2.6 on 2023-11-01 22:50

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0006_alter_flight_options_alter_route_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airport.models.airport_image_file_path
            ),
        ),
    ]
